apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  labels:
    app: go-app
    heritage: NOT-Helm
  annotations:
    "helm.sh/hook-weight": "5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: go-app
          image: victor23d/go-app:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /livenessProbe
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 120
          readinessProbe:
            httpGet:
              path: /readinessProbe
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 120
          lifecycle:
            postStart:
              exec:
                command: ["sh", "-c", "/app/scripts/PostStart.sh"]
          envFrom:
          - configMapRef:
              name: go-app-env
          # - secretRef:
          #     name: go-app
          # volumeMounts:
          #   - name: server-tools-secret
          #     mountPath: /secrets/server-tools-secret
      # volumes:
        # - name: server-tools-secret
          # secret:
          #   secretName: server-tools-secret

