apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  labels:
    app: go-app
  # annotations:
    # "helm.sh/hook-weight": "5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: go-app
          image: victor23d/go-app:latest
          command: ["sh", "-c", "/root/app -qa"]
          ports:
            - containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /livenessProbe
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 60
          # readinessProbe:
          #   httpGet:
          #     path: /readinessProbe
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 60
          # lifecycle:
          #   postStart:
          #     exec:
          #       command: ["sh", "-c", "/app/scripts/PostStart.sh"]
          # envFrom:
          # - configMapRef:
          #     name: env-config
          # - secretRef:
          #     name: secret-config
          # volumeMounts:
          #   - name: server-tools-secret
          #     mountPath: /secrets/server-tools-secret
      # volumes:
        # - name: server-tools-secret
          # secret:
          #   secretName: server-tools-secret

