apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: go-app
  labels:
    app: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
      name: go-app
    spec:
      containers:
        - name: go-app
          image: victor23d/go-app
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /readinessProbe
              port: 8080
          lifecycle:
            postStart:
              exec:
                # command: ["sh", "-c", "/app/scripts/PostStart.sh"]
                command: ["sh", "-c", "/app/scripts/db-migrate.sh"]
                # command: ["ls", "-R"]

