apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-job
  labels:
    app: migrate-job
    chart: helm-server-tools-0.1.0
    heritage: Helm
    release: v123
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      terminationGracePeriodSeconds: 30
      restartPolicy: Never
      containers:
        - name: migrate-job
          image: victor23d/go-app:latest
          imagePullPolicy: Always
          command:
              - "/app/scripts/migrate-job.sh"
              # ["sleep", "60"]


