apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  labels:
    app: db-migrate
    chart: helm-server-tools-0.1.0
    heritage: Helm
    release: v123
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      terminationGracePeriodSeconds: 30
      restartPolicy: Never
      containers:
        - name: db-migrate
          image: victor23d/go-app:latest
          command:
              - "/app/scripts/db-migrate.sh"
              # ["sleep", "60"]


