apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-job
  labels:
    app: migrate-job
    heritage: NOT-Helm
  annotations:
    # "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  completions: 1
  backoffLimit: 0
  ttlSecondsAfterFinished: 100
  template:
    spec:
      terminationGracePeriodSeconds: 30
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      containers:

        - name: go-app
          image: victor23d/go-app:latest
          imagePullPolicy: Always
          command:
            - "/app/scripts/migrate-job.sh"

          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /livenessProbe
              port: 8080
          readinessProbe:
            httpGet:
              path: /readinessProbe
              port: 8080
          envFrom:
          - configMapRef:
              name: go-app
          - secretRef:
              name: go-app
          volumeMounts:
            - name: server-tools-secret
              mountPath: /secrets/server-tools-secret
      volumes:
        - name: server-tools-secret
          secret:
            secretName: server-tools-secret

