apiVersion: v1
kind: Service
metadata:
  name: bench
  labels:
    app: bench
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: bench
  # type: LoadBalancer
  type: ClusterIP

---
