apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter
  labels:
    role: postgres
    team: frontend
spec:
  selector:
    matchLabels:
      app: postgres-exporter
  endpoints:
  - port: pe
  - interval: 3s
