apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  labels:
    app: postgres-exporter
spec:
  ports:
    - name: pe
      port: 9187
  selector:
    app: postgres-exporter
  type: NodePort

---
