apiVersion: v1
kind: Service
metadata:
  name: jetty
  labels:
    app: jetty
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8443
    - name: https
      port: 8080
      targetPort: 8080
  selector:
    app: jetty
  type: NodePort
  # type: LoadBalancer
  externalTrafficPolicy: Local
